### PR TITLE
Implement QEMU PCILeech plugin

### PR DESCRIPTION
**Pull request by Zero-Tang**
The QEMU virtual PCILeech device is still awaiting merging.

### CODE REVIEW

**Comment by ufrisk** [comment]
Thank you for this PR. It looks really nice.

I'm looking forward to test it and give it a try when I'm back home in about 2 weeks from now.

This is really nice, since unlike the previous qemu integration, this actually enables you to emulate a PCILeech device and to do testing of firmware and/or security research with this emulated device in a convenient way.

Thank You for contributing to the PCILeech project.

**Comment by ufrisk** [comment]
And it's merged. I'll look into this a bit more later today. Thank You for this contribution.

**Comment by ufrisk** [comment]
I made some minor changes to the plugin (added dll version info on Windows) and published it in the default packaged builds available for download.

When/If the PCILeech device gets merged into mainline QEMU please let me know. It would be very nice to know if it's there and then I can add a proper wiki entry for this device etc.

Once again Thank You for this very nice contribution.

**Comment by Zero-Tang** [comment]
It's not merged into QEMU mainline yet. So far I have received only [one comment about the use of QEMU internal APIs](https://lists.gnu.org/archive/html/qemu-devel/2024-08/msg04217.html). This comment also conjectured that QEMU upstream probably would not be interested in it.

I suggest let's make a QEMU fork, maintain it, and let time prove its usefulness. Even in worst case scenario, this plugin won't go to waste.

**Comment by ufrisk** [comment]
Thank You for the follow-up even though I wish the news could be better.

I'll keep the plugin as such in the plugins repo, but since support won't be included in mainline QEMU I'll leave it at that, i.e. I'm not going to ship pre-compiled plugin versions in the release builds from now on.

Maintaining a QEMU fork is a good idea, or maybe the users could just apply the patches themselves (that would be easier). I kind of feel that I already have way too much on my plate to handle so I unfortunately won't be able to maintain the fork myself.

**Comment by Zero-Tang** [comment]
OK then, I will maintain [QEMU fork](https://github.com/qemu-pcileech/qemu) and this plugin on my own. But please leave a note in your main repository that this plugin is available.

**Comment by ufrisk** [comment]
Many thanks for this. I'm just wary of taking on additional support burden myself.

I should add this as a supported device in the [LeechCore wiki](https://github.com/ufrisk/LeechCore/wiki) - so it's clear it's around though. If you're advanced enough to install your own QEMU fork you should be able to build the small leechcore plugin as well.

Or if you wish you could push a small documentation for it (just the .md file, not updated sidebars etc.) to the wiki, if not I'll probably look into it this weekend.

**Pull request merged**
