### PR TITLE
Add hugepage qemu memory type support

### PR DESCRIPTION
**Pull request by aodzip**
This will allow leechcore work with hugepage enabled qemu vm. This method required qemu pid to work, it will scan qemu fds and find (deleted) hugepage file. Tested with libvirtd created qemu vm.

libvirtd xml
```xml
  <memoryBacking>
    <hugepages>
      <page size="1048576" unit="KiB"/>
    </hugepages>
    <access mode="shared"/>
  </memoryBacking>
```

### CODE REVIEW

**Comment by ufrisk** [comment]
Hi and many thanks for this very nice pull request.

I'll do some testing on my side and rearrange some parameters and then merge it. I hope to do this as soon as possible.

To whom should I give credits in the readme?

**Comment by aodzip** [comment]
cedits use my github account is okay.

**Comment by aodzip** [comment]
Additional:

libvirt qemu will delete the file in hugepagefs automatically in my system Debian 12, scan in proc/fd is necessery. 

I think this (qemu delete after open) behavior is for easily recycle hugepage resources when qemu process crash. It will be clean by linux kernel.

maybe this method ( scan for fd ) is also work for shm and another libvirt shared memory backend called memfd.

**Comment by ufrisk** [comment]
I've added and changed it around a bit mainly since I didn't wish to change the current syntax used. I hope this should work well. Huge thanks for the contribution and please let me know if you should feel anything is less than optimal with the updated version.

Documentation at: https://github.com/ufrisk/LeechCore/wiki/Device_QEMU

image

**Pull request merged**
